#   conda env create -f environment.yml
name: docker_image_name
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # make the environment that works to support your project
  # Note - not using Biopython, but may in future version (to read in fasta)
  - python=3.7.3
  - biopython
  - pandas
